network:
  version: 2
  renderer: NetworkManager
  ethernets:
      eth0:
          addresses:
              - 10.0.0.1/24
          nameservers:
              addresses: [10.0.0.1]
          routes:
              - to: 10.0.0.1
                via: 10.0.0.1
